# Generated by Django 5.0.1 on 2024-02-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simple', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydb',
            name='joined_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='mydb',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
